
'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic


Partial Public Class award

    Public Property name As String

    Public Property id As Long



    Public Overridable Property club_award As ICollection(Of club_award) = New HashSet(Of club_award)


End Class
