
'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic


Partial Public Class classification

    Public Property name As String

    Public Property id As Long



    Public Overridable Property club_classification As ICollection(Of club_classification) = New HashSet(Of club_classification)


End Class
