'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class club_classification
    Public Property club_id As Nullable(Of Long)
    Public Property classification_id As Nullable(Of Long)
    Public Property sort_key As Long

    Public Overridable Property classification As classification
    Public Overridable Property club As club

End Class
