'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class club
    Public Property short_name As String
    Public Property name As String
    Public Property id As Long
    Public Property min_score As Nullable(Of Long)
    Public Property max_score As Nullable(Of Long)
    Public Property min_score_for_award As Nullable(Of Long)

End Class
