'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class club_medium
    Public Property club_id As Nullable(Of Long)
    Public Property medium_id As Nullable(Of Long)
    Public Property sort_key As Long

    Public Overridable Property club As club
    Public Overridable Property medium As medium

End Class
