
'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic


Partial Public Class CompetitionEntry

    Public Property Photo_ID As Long

    Public Property Title As String

    Public Property Maker As String

    Public Property Classification As String

    Public Property Medium As String

    Public Property Theme As String

    Public Property Competition_Date_1 As String

    Public Property Score_1 As Nullable(Of Long)

    Public Property Award As String

    Public Property Image_File_Name As String

    Public Property Display_Sequence As Nullable(Of Long)

    Public Property Server_Entry_ID As Nullable(Of Long)


End Class
