'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class rpsEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=rpsEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property awards() As DbSet(Of award)
    Public Overridable Property classifications() As DbSet(Of classification)
    Public Overridable Property clubs() As DbSet(Of club)
    Public Overridable Property CompetitionEntries() As DbSet(Of CompetitionEntry)
    Public Overridable Property media() As DbSet(Of medium)

End Class
